package com.alexgaoyh.MutiModule.persist.sysman;

public class SysmanUserRoleRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanuserrolerel.sysmanUserId
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    private Integer sysmanUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanuserrolerel.sysmanRoleId
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    private Integer sysmanRoleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanuserrolerel.sysmanUserId
     *
     * @return the value of sysmanuserrolerel.sysmanUserId
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    public Integer getSysmanUserId() {
        return sysmanUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanuserrolerel.sysmanUserId
     *
     * @param sysmanUserId the value for sysmanuserrolerel.sysmanUserId
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    public void setSysmanUserId(Integer sysmanUserId) {
        this.sysmanUserId = sysmanUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanuserrolerel.sysmanRoleId
     *
     * @return the value of sysmanuserrolerel.sysmanRoleId
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    public Integer getSysmanRoleId() {
        return sysmanRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanuserrolerel.sysmanRoleId
     *
     * @param sysmanRoleId the value for sysmanuserrolerel.sysmanRoleId
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    public void setSysmanRoleId(Integer sysmanRoleId) {
        this.sysmanRoleId = sysmanRoleId;
    }
}