package com.alexgaoyh.MutiModule.persist.sysman;

import com.alexgaoyh.MutiModule.persist.sysman.SysmanRole;
import com.alexgaoyh.MutiModule.persist.sysman.SysmanRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysmanRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    int countByExample(SysmanRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    int deleteByExample(SysmanRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    int insert(SysmanRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    int insertSelective(SysmanRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    List<SysmanRole> selectByExample(SysmanRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    SysmanRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysmanRole record, @Param("example") SysmanRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    int updateByExample(@Param("record") SysmanRole record, @Param("example") SysmanRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    int updateByPrimaryKeySelective(SysmanRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    int updateByPrimaryKey(SysmanRole record);
}