package com.alexgaoyh.MutiModule.persist.sysman;

import java.io.Serializable;
import java.util.Date;

public class SysmanUser implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanuser.id
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanuser.deleteFlag
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    private Integer deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanuser.createTime
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanuser.name
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanuser.password
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanuser.id
     *
     * @return the value of sysmanuser.id
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanuser.id
     *
     * @param id the value for sysmanuser.id
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanuser.deleteFlag
     *
     * @return the value of sysmanuser.deleteFlag
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanuser.deleteFlag
     *
     * @param deleteflag the value for sysmanuser.deleteFlag
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanuser.createTime
     *
     * @return the value of sysmanuser.createTime
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanuser.createTime
     *
     * @param createtime the value for sysmanuser.createTime
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanuser.name
     *
     * @return the value of sysmanuser.name
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanuser.name
     *
     * @param name the value for sysmanuser.name
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanuser.password
     *
     * @return the value of sysmanuser.password
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanuser.password
     *
     * @param password the value for sysmanuser.password
     *
     * @mbggenerated Sat May 23 11:26:37 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }
}