package com.alexgaoyh.MutiModule.persist.sysman;

public class SysmanUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanuser.id
     *
     * @mbggenerated Mon May 04 14:29:46 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanuser.name
     *
     * @mbggenerated Mon May 04 14:29:46 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanuser.password
     *
     * @mbggenerated Mon May 04 14:29:46 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanuser.deleteFlag
     *
     * @mbggenerated Mon May 04 14:29:46 CST 2015
     */
    private Integer deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanuser.id
     *
     * @return the value of sysmanuser.id
     *
     * @mbggenerated Mon May 04 14:29:46 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanuser.id
     *
     * @param id the value for sysmanuser.id
     *
     * @mbggenerated Mon May 04 14:29:46 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanuser.name
     *
     * @return the value of sysmanuser.name
     *
     * @mbggenerated Mon May 04 14:29:46 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanuser.name
     *
     * @param name the value for sysmanuser.name
     *
     * @mbggenerated Mon May 04 14:29:46 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanuser.password
     *
     * @return the value of sysmanuser.password
     *
     * @mbggenerated Mon May 04 14:29:46 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanuser.password
     *
     * @param password the value for sysmanuser.password
     *
     * @mbggenerated Mon May 04 14:29:46 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanuser.deleteFlag
     *
     * @return the value of sysmanuser.deleteFlag
     *
     * @mbggenerated Mon May 04 14:29:46 CST 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanuser.deleteFlag
     *
     * @param deleteflag the value for sysmanuser.deleteFlag
     *
     * @mbggenerated Mon May 04 14:29:46 CST 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}