package com.alexgaoyh.MutiModule.persist.sysman;

import com.alexgaoyh.MutiModule.persist.sysman.SysmanUser;
import com.alexgaoyh.MutiModule.persist.sysman.SysmanUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysmanUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuser
     *
     * @mbggenerated Mon May 04 11:13:14 CST 2015
     */
    int countByExample(SysmanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuser
     *
     * @mbggenerated Mon May 04 11:13:14 CST 2015
     */
    int deleteByExample(SysmanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuser
     *
     * @mbggenerated Mon May 04 11:13:14 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuser
     *
     * @mbggenerated Mon May 04 11:13:14 CST 2015
     */
    int insert(SysmanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuser
     *
     * @mbggenerated Mon May 04 11:13:14 CST 2015
     */
    int insertSelective(SysmanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuser
     *
     * @mbggenerated Mon May 04 11:13:14 CST 2015
     */
    List<SysmanUser> selectByExample(SysmanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuser
     *
     * @mbggenerated Mon May 04 11:13:14 CST 2015
     */
    SysmanUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuser
     *
     * @mbggenerated Mon May 04 11:13:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysmanUser record, @Param("example") SysmanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuser
     *
     * @mbggenerated Mon May 04 11:13:14 CST 2015
     */
    int updateByExample(@Param("record") SysmanUser record, @Param("example") SysmanUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuser
     *
     * @mbggenerated Mon May 04 11:13:14 CST 2015
     */
    int updateByPrimaryKeySelective(SysmanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuser
     *
     * @mbggenerated Mon May 04 11:13:14 CST 2015
     */
    int updateByPrimaryKey(SysmanUser record);
}