package com.alexgaoyh.MutiModule.persist.sysman;

import com.alexgaoyh.MutiModule.persist.sysman.SysmanResource;
import com.alexgaoyh.MutiModule.persist.sysman.SysmanResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysmanResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanresource
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    int countByExample(SysmanResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanresource
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    int deleteByExample(SysmanResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanresource
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanresource
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    int insert(SysmanResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanresource
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    int insertSelective(SysmanResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanresource
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    List<SysmanResource> selectByExample(SysmanResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanresource
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    SysmanResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanresource
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysmanResource record, @Param("example") SysmanResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanresource
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    int updateByExample(@Param("record") SysmanResource record, @Param("example") SysmanResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanresource
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    int updateByPrimaryKeySelective(SysmanResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanresource
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    int updateByPrimaryKey(SysmanResource record);
    
    /**
     * 根据角色id，获取到这个角色下所包含的资源集合
     * @param id 角色id
     * @return 符合条件的资源list集合
     */
    List<SysmanResource> selectResourceListBySysmanRoleId(Integer id);
}