package com.alexgaoyh.MutiModule.persist.sysman;

import com.alexgaoyh.MutiModule.persist.sysman.SysmanUserRoleRelExample;
import com.alexgaoyh.MutiModule.persist.sysman.SysmanUserRoleRel;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SysmanUserRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    int countByExample(SysmanUserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    int deleteByExample(SysmanUserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    int deleteByPrimaryKey(SysmanUserRoleRel key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    int insert(SysmanUserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    int insertSelective(SysmanUserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    List<SysmanUserRoleRel> selectByExample(SysmanUserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysmanUserRoleRel record, @Param("example") SysmanUserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Sat May 23 13:20:15 CST 2015
     */
    int updateByExample(@Param("record") SysmanUserRoleRel record, @Param("example") SysmanUserRoleRelExample example);
    
    /**
     * 根据sysmanUserId删除关联关系
     * @param sysmanUserId	sysmanUser表中id，用户id
     * @return
     */
    int deleteByUserId(@Param("sysmanUserId")Integer sysmanUserId);
    
    /**
     * 批量插入数据
     * @param list	SysmanUserRoleRel对象的集合
     * @return
     */
    int insertbatch(List<SysmanUserRoleRel> list);
}