package com.alexgaoyh.MutiModule.persist.sysman;

import java.util.Date;

public class SysmanRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanrole.id
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanrole.deleteFlag
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    private Integer deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanrole.createTime
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanrole.name
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanrole.description
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanrole.id
     *
     * @return the value of sysmanrole.id
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanrole.id
     *
     * @param id the value for sysmanrole.id
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanrole.deleteFlag
     *
     * @return the value of sysmanrole.deleteFlag
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanrole.deleteFlag
     *
     * @param deleteflag the value for sysmanrole.deleteFlag
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanrole.createTime
     *
     * @return the value of sysmanrole.createTime
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanrole.createTime
     *
     * @param createtime the value for sysmanrole.createTime
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanrole.name
     *
     * @return the value of sysmanrole.name
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanrole.name
     *
     * @param name the value for sysmanrole.name
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanrole.description
     *
     * @return the value of sysmanrole.description
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanrole.description
     *
     * @param description the value for sysmanrole.description
     *
     * @mbggenerated Sat May 23 12:13:24 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}