package com.alexgaoyh.MutiModule.persist.sysman;

import java.io.Serializable;

public class SysmanRoleResourceRel implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanroleresourcerel.sysmanRoleId
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    private Integer sysmanRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanroleresourcerel.sysmanResourceId
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    private Integer sysmanResourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanroleresourcerel.sysmanRoleId
     *
     * @return the value of sysmanroleresourcerel.sysmanRoleId
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    public Integer getSysmanRoleId() {
        return sysmanRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanroleresourcerel.sysmanRoleId
     *
     * @param sysmanRoleId the value for sysmanroleresourcerel.sysmanRoleId
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    public void setSysmanRoleId(Integer sysmanRoleId) {
        this.sysmanRoleId = sysmanRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanroleresourcerel.sysmanResourceId
     *
     * @return the value of sysmanroleresourcerel.sysmanResourceId
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    public Integer getSysmanResourceId() {
        return sysmanResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanroleresourcerel.sysmanResourceId
     *
     * @param sysmanResourceId the value for sysmanroleresourcerel.sysmanResourceId
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    public void setSysmanResourceId(Integer sysmanResourceId) {
        this.sysmanResourceId = sysmanResourceId;
    }
}