package com.alexgaoyh.MutiModule.persist.sysman;

import com.alexgaoyh.MutiModule.persist.sysman.SysmanRoleResourceRelExample;
import com.alexgaoyh.MutiModule.persist.sysman.SysmanRoleResourceRel;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysmanRoleResourceRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanroleresourcerel
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    int countByExample(SysmanRoleResourceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanroleresourcerel
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    int deleteByExample(SysmanRoleResourceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanroleresourcerel
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    int deleteByPrimaryKey(SysmanRoleResourceRel key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanroleresourcerel
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    int insert(SysmanRoleResourceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanroleresourcerel
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    int insertSelective(SysmanRoleResourceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanroleresourcerel
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    List<SysmanRoleResourceRel> selectByExample(SysmanRoleResourceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanroleresourcerel
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysmanRoleResourceRel record, @Param("example") SysmanRoleResourceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanroleresourcerel
     *
     * @mbggenerated Sat May 23 13:19:01 CST 2015
     */
    int updateByExample(@Param("record") SysmanRoleResourceRel record, @Param("example") SysmanRoleResourceRelExample example);
}