package com.alexgaoyh.MutiModule.persist.sysman;

import java.io.Serializable;
import java.util.Date;

public class SysmanResource implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.id
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.deleteFlag
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    private Integer deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.createTime
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.name
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.description
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.href
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    private String href;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.resourceType
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    private Integer resourcetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.parentId
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    private Integer parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.id
     *
     * @return the value of sysmanresource.id
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.id
     *
     * @param id the value for sysmanresource.id
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.deleteFlag
     *
     * @return the value of sysmanresource.deleteFlag
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.deleteFlag
     *
     * @param deleteflag the value for sysmanresource.deleteFlag
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.createTime
     *
     * @return the value of sysmanresource.createTime
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.createTime
     *
     * @param createtime the value for sysmanresource.createTime
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.name
     *
     * @return the value of sysmanresource.name
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.name
     *
     * @param name the value for sysmanresource.name
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.description
     *
     * @return the value of sysmanresource.description
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.description
     *
     * @param description the value for sysmanresource.description
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.href
     *
     * @return the value of sysmanresource.href
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.href
     *
     * @param href the value for sysmanresource.href
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.resourceType
     *
     * @return the value of sysmanresource.resourceType
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public Integer getResourcetype() {
        return resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.resourceType
     *
     * @param resourcetype the value for sysmanresource.resourceType
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public void setResourcetype(Integer resourcetype) {
        this.resourcetype = resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.parentId
     *
     * @return the value of sysmanresource.parentId
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.parentId
     *
     * @param parentid the value for sysmanresource.parentId
     *
     * @mbggenerated Sat May 23 12:18:15 CST 2015
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }
}