package com.alexgaoyh.MutiModule.persist.demo;

public class Demo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbggenerated Wed Apr 22 11:43:34 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.deleteFlagState
     *
     * @mbggenerated Wed Apr 22 11:43:34 CST 2015
     */
    private Integer deleteflagstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.name
     *
     * @mbggenerated Wed Apr 22 11:43:34 CST 2015
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.id
     *
     * @return the value of demo.id
     *
     * @mbggenerated Wed Apr 22 11:43:34 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.id
     *
     * @param id the value for demo.id
     *
     * @mbggenerated Wed Apr 22 11:43:34 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.deleteFlagState
     *
     * @return the value of demo.deleteFlagState
     *
     * @mbggenerated Wed Apr 22 11:43:34 CST 2015
     */
    public Integer getDeleteflagstate() {
        return deleteflagstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.deleteFlagState
     *
     * @param deleteflagstate the value for demo.deleteFlagState
     *
     * @mbggenerated Wed Apr 22 11:43:34 CST 2015
     */
    public void setDeleteflagstate(Integer deleteflagstate) {
        this.deleteflagstate = deleteflagstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.name
     *
     * @return the value of demo.name
     *
     * @mbggenerated Wed Apr 22 11:43:34 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.name
     *
     * @param name the value for demo.name
     *
     * @mbggenerated Wed Apr 22 11:43:34 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }
}