package com.alexgaoyh.MutiModule.persist.demo;

import java.io.Serializable;
import java.util.Date;

public class Demo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.createTime
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.deleteFlag
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.name
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demo
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.id
     *
     * @return the value of demo.id
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.id
     *
     * @param id the value for demo.id
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.createTime
     *
     * @return the value of demo.createTime
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.createTime
     *
     * @param createTime the value for demo.createTime
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.deleteFlag
     *
     * @return the value of demo.deleteFlag
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.deleteFlag
     *
     * @param deleteFlag the value for demo.deleteFlag
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.name
     *
     * @return the value of demo.name
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.name
     *
     * @param name the value for demo.name
     *
     * @mbggenerated Mon Jul 13 12:21:38 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }
}