package com.alexgaoyh.MutiModule.persist.sysman.SysmanUserRoleRel;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SysmanUserRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Mon Jul 13 09:04:40 CST 2015
     */
    int countByExample(SysmanUserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Mon Jul 13 09:04:40 CST 2015
     */
    int deleteByExample(SysmanUserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Mon Jul 13 09:04:40 CST 2015
     */
    int deleteByPrimaryKey(SysmanUserRoleRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Mon Jul 13 09:04:40 CST 2015
     */
    int insert(SysmanUserRoleRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Mon Jul 13 09:04:40 CST 2015
     */
    int insertSelective(SysmanUserRoleRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Mon Jul 13 09:04:40 CST 2015
     */
    List<SysmanUserRoleRelKey> selectByExample(SysmanUserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Mon Jul 13 09:04:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysmanUserRoleRelKey record, @Param("example") SysmanUserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanuserrolerel
     *
     * @mbggenerated Mon Jul 13 09:04:40 CST 2015
     */
    int updateByExample(@Param("record") SysmanUserRoleRelKey record, @Param("example") SysmanUserRoleRelExample example);
    
    /**
     * 根据sysmanUserId删除关联关系
     * @param sysmanUserId	sysmanUser表中id，用户id
     * @return
     */
    int deleteByUserId(@Param("sysmanUserId")Integer sysmanUserId);
    
    /**
     * 批量插入数据
     * @param list	SysmanUserRoleRel对象的集合
     * @return
     */
    int insertbatch(List<SysmanUserRoleRelKey> list);
}