package com.alexgaoyh.MutiModule.persist.sysman.SysmanRole;

import java.io.Serializable;
import java.util.Date;

public class SysmanRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanrole.id
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanrole.deleteFlag
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanrole.createTime
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanrole.name
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanrole.description
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanrole.id
     *
     * @return the value of sysmanrole.id
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanrole.id
     *
     * @param id the value for sysmanrole.id
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanrole.deleteFlag
     *
     * @return the value of sysmanrole.deleteFlag
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanrole.deleteFlag
     *
     * @param deleteFlag the value for sysmanrole.deleteFlag
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanrole.createTime
     *
     * @return the value of sysmanrole.createTime
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanrole.createTime
     *
     * @param createTime the value for sysmanrole.createTime
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanrole.name
     *
     * @return the value of sysmanrole.name
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanrole.name
     *
     * @param name the value for sysmanrole.name
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanrole.description
     *
     * @return the value of sysmanrole.description
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanrole.description
     *
     * @param description the value for sysmanrole.description
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
    
    
	//add alexgaoyh 20150602 重写方法，用于判断两个对象的值是否相等
  	@Override
  	public int hashCode() {
  		final int prime = 31;
  		int result = 1;
  		result = prime * result + id;
  		return result;
  	}

  	@Override
  	public boolean equals(Object obj) {
  		if (this == obj) {
  			return true;
  		}
  		if (obj == null) {
  			return false;
  		}
  		if (getClass() != obj.getClass()) {
  			return false;
  		}
  		final SysmanRole other = (SysmanRole) obj;
  		if (id != other.id) {
  			return false;
  		}
  		return true;
  	}
}