package com.alexgaoyh.MutiModule.persist.sysman.SysmanRole;

import com.alexgaoyh.MutiModule.persist.sysman.SysmanRole.SysmanRole;
import com.alexgaoyh.MutiModule.persist.sysman.SysmanRole.SysmanRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysmanRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    int countByExample(SysmanRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    int deleteByExample(SysmanRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    int insert(SysmanRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    int insertSelective(SysmanRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    int deleteLogicByIds(@Param("deleteFlag") int deleteFlag, @Param("ids") Integer[] ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    List<SysmanRole> selectByExample(SysmanRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    SysmanRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysmanRole record, @Param("example") SysmanRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    int updateByExample(@Param("record") SysmanRole record, @Param("example") SysmanRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    int updateByPrimaryKeySelective(SysmanRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmanrole
     *
     * @mbggenerated Mon Jul 13 08:54:07 CST 2015
     */
    int updateByPrimaryKey(SysmanRole record);
    
    /**
     * 根据用户id，获取这个用户所包含的所有角色信息集合
     * @param id 用户id
     * @return  返回这个用户id所包含的角色集合
     */
    List<SysmanRole> selectRoleListBySysmanUserId(Integer id);
}