package com.alexgaoyh.MutiModule.persist.sysman.SysmanResource;

import java.io.Serializable;
import java.util.Date;

public class SysmanResource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.id
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.deleteFlag
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.createTime
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.name
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.description
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.href
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    private String href;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.resourceType
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    private Integer resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmanresource.parentId
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sysmanresource
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.id
     *
     * @return the value of sysmanresource.id
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.id
     *
     * @param id the value for sysmanresource.id
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.deleteFlag
     *
     * @return the value of sysmanresource.deleteFlag
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.deleteFlag
     *
     * @param deleteFlag the value for sysmanresource.deleteFlag
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.createTime
     *
     * @return the value of sysmanresource.createTime
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.createTime
     *
     * @param createTime the value for sysmanresource.createTime
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.name
     *
     * @return the value of sysmanresource.name
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.name
     *
     * @param name the value for sysmanresource.name
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.description
     *
     * @return the value of sysmanresource.description
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.description
     *
     * @param description the value for sysmanresource.description
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.href
     *
     * @return the value of sysmanresource.href
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.href
     *
     * @param href the value for sysmanresource.href
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.resourceType
     *
     * @return the value of sysmanresource.resourceType
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public Integer getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.resourceType
     *
     * @param resourceType the value for sysmanresource.resourceType
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public void setResourceType(Integer resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmanresource.parentId
     *
     * @return the value of sysmanresource.parentId
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmanresource.parentId
     *
     * @param parentId the value for sysmanresource.parentId
     *
     * @mbggenerated Mon Jul 13 08:49:47 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}